### ISSUE TITLE
'int' object is not subscriptable

### ISSUE THREAD

**Issue by ggg17226** [BurguerJohn/Dain-App#16]
i get this crash when i runing the program
```
App Crash Log Traceback (most recent call last):
  File "my_design.py", line 72, in run
  File "my_DAIN_class.py", line 1190, in RenderVideo
  File "my_DAIN_class.py", line 1022, in StepRenderInterpolation
TypeError: 'int' object is not subscriptable
```

OS: win10 20h2 10.0.19042.746
CPU: i9-9900k@4.9G
MEM: 32G DDR4
GPU: RTX3090 whit driver version 457.51

**Comment by Bostwickenator** [comment]
Ditto
