### ISSUE TITLE
error when it is more then 1 input file

### ISSUE THREAD

**Issue by severyanin-lub** [BurguerJohn/Dain-App#3]
When i try to render 2 or more files...

App Crash Log Traceback (most recent call last):
  File "my_design.py", line 72, in run
  File "my_DAIN_class.py", line 1190, in RenderVideo
  File "my_DAIN_class.py", line 1069, in StepRenderInterpolation
UnboundLocalError: local variable 'loops' referenced before assignment

Feel sad because I have about 200 little videos with 10-15 framerate... it will be hard to do it manual

**Comment by BurguerJohn** [comment]
Are you using the github / 1.0 version? I though this bug was already fixed.

**Comment by severyanin-lub** [comment]
Yes, I downloaded program today from github. 
DAIN_APP Alpha 1.0

**Comment by severyanin-lub** [comment]
is it some way to solve this problem? I have about 150 videos more... :(

**Comment by Zhou-JinYuan** [comment]
input ANY a video, check the perfect loop option, finish all perform once, then start what u wanna do. I dont know why, but it did effect
