### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by michasrutek** [BurguerJohn/Dain-App#8]
When I trying to render a video in step 3 (1 and 2 step working without problems) I've got message.
Crash [Saved on crash_log.txt]:
Check out Discord for possible solutions:
Check Errors fix on Discord. 

Error: list index out of range

In crash log I've got message:
App Crash Log Traceback (most recent call last):
  File "my_design.py", line 72, in run
  File "my_DAIN_class.py", line 1194, in RenderVideo
  File "my_DAIN_class.py", line 1144, in StepCreateVideo
  File "my_DAIN_class.py", line 526, in create_video2
IndexError: list index out of range

I have program, source video, target place for video in names and subdirectories without spaces.
I've got this comunicate before 3rd step and error when I click YES. When clicking NO program don't start.
This may rename a few files inside the interpolated_frames folder, are you sure?
Settings for render is in images:
![screen 7](https://user-images.githubusercontent.com/65863630/103432285-fb8ad480-4bdc-11eb-86f2-23de7a76b99c.PNG)
![1 screen](https://user-images.githubusercontent.com/65863630/103432287-fc236b00-4bdc-11eb-83b9-1c9a27a492b7.PNG)
![2 screen](https://user-images.githubusercontent.com/65863630/103432288-fc236b00-4bdc-11eb-8a76-6e534218aecf.PNG)
![3 screen](https://user-images.githubusercontent.com/65863630/103432289-fcbc0180-4bdc-11eb-87c0-9f2e2e86152e.PNG)
![4 screen](https://user-images.githubusercontent.com/65863630/103432290-fcbc0180-4bdc-11eb-9d69-a78082457d28.PNG)
![5 screen](https://user-images.githubusercontent.com/65863630/103432291-fd549800-4bdc-11eb-975a-18358ce84a7c.PNG)
![6 screen](https://user-images.githubusercontent.com/65863630/103432292-fd549800-4bdc-11eb-86e7-7be3d98a6846.PNG)

Specification is:
I7-3770
16GB (4x4GB) DDR3 1600MHz Dual channel
GTX 1060 6GB
Gigabyte Z77-DS3H (rev 1.0)
Files and program in 2 separate HDD drives.
What do I need to do to render video without errors?

Hardware chart from 1st step to 3rd and error
![Hardware chart](https://user-images.githubusercontent.com/65863630/103432373-2a557a80-4bde-11eb-803a-78a9069dbb27.PNG)

From text console in another file:
[Log.txt](https://github.com/BurguerJohn/Dain-App/files/5758558/Log.txt)

PS: Sorry for my English if It's wrong.

**Comment by YiWeiHuang-stack** [comment]
你这X:50 Y:50视频都切成片了吧(*^_^*)
